SELECT 
    "loan_applications_history_stacked"."loan_amnt" AS "loan_amnt",
    "loan_applications_history_stacked"."funded_amnt" AS "funded_amnt",
    "loan_applications_history_stacked"."funded_amnt_inv" AS "funded_amnt_inv",
    "loan_applications_history_stacked"."term" AS "term",
    "loan_applications_history_stacked"."int_rate" AS "int_rate",
    "loan_applications_history_stacked"."installment" AS "installment",
    "loan_applications_history_stacked"."grade" AS "grade",
    "loan_applications_history_stacked"."sub_grade" AS "sub_grade",
    "loan_applications_history_stacked"."issue_date" AS "issue_date",
    "loan_applications_history_stacked"."zip_code" AS "zip_code",
    "loan_applications_history_stacked"."addr_state" AS "addr_state",
    "loan_applications_history_stacked"."dti" AS "dti",
    "loan_applications_history_stacked"."emp_title" AS "emp_title",
    "loan_applications_history_stacked"."emp_length_month" AS "emp_length_month",
    "loan_applications_history_stacked"."home_ownership" AS "home_ownership",
    "loan_applications_history_stacked"."verification_status" AS "verification_status",
    "loan_applications_history_stacked"."loan_status" AS "loan_status",
    "loan_applications_history_stacked"."pymnt_plan" AS "pymnt_plan",
    "loan_applications_history_stacked"."purpose" AS "purpose",
    "loan_applications_history_stacked"."title" AS "title",
    "loan_metrics_by_state"."loan_amnt_avg" AS "state_loan_amnt_avg",
    "loan_metrics_by_state"."loan_amnt_sum" AS "state_loan_amnt_sum",
    "loan_metrics_by_state"."int_rate_min" AS "state_int_rate_min",
    "loan_metrics_by_state"."int_rate_max" AS "state_int_rate_max",
    "loan_metrics_by_state"."int_rate_avg" AS "state_int_rate_avg",
    "loan_metrics_by_state"."installment_avg" AS "state_installment_avg",
    "loan_metrics_by_state"."dti_min" AS "state_dti_min",
    "loan_metrics_by_state"."dti_max" AS "state_dti_max",
    "loan_metrics_by_state"."dti_avg" AS "state_dti_avg",
    "loan_metrics_by_state"."count" AS "state_count"
  FROM "Design_MLCREDITSCORING_loan_applications_history_stacked" "loan_applications_history_stacked"
  LEFT JOIN "Design_MLCREDITSCORING_loan_metrics_by_state" "loan_metrics_by_state"
    ON "loan_applications_history_stacked"."addr_state" = "loan_metrics_by_state"."addr_state"